steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test:unit']
- name: 'docker/compose:1.15.0'
  args: ['-f', 'docker-compose.it.yaml', 'up', '--abort-on-container-exit', '--build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/dian:latest', '.']
images: ['gcr.io/$PROJECT_ID/dian:latest']
