---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "dian-service"
  namespace: "default"
  labels:
    app: "dian"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
  selector:
    app: "dian"
  type: "LoadBalancer"
  loadBalancerIP: ""
