---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "dian"
  namespace: "default"
  labels:
    app: "dian"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "dian"
  template:
    metadata:
      labels:
        app: "dian"
    spec:
      containers:
      - name: "dian"
        image: "gcr.io/first-spike-1234/dian:latest"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "dian-hpa"
  namespace: "default"
  labels:
    app: "dian"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "dian"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
